### ISSUE TITLE
missing yield

### ISSUE THREAD

**Issue by yelouafi** [nikgraf/CarteJaune#6]
I think there is missing `yield` statement here

https://github.com/nikgraf/CarteJaune/blob/master/sagas/saveVaccinations.js#L22

**Comment by nikgraf** [comment]
that explains why the tests were so weird :smile: - trying to get the app running again after upgrading all the dependencies right now. thx for looking into the sagas here! :+1:

**Comment by nikgraf** [comment]
resolved in: https://github.com/nikgraf/CarteJaune/commit/5d48f59449ba025be94464e80f41753ed86541d3
